import './style.css';

type Product={id:string,name:string,price:number,varadero:number,matanzas:number};
type Entry={id:string,productId:string,qty:number,location:'Varadero'|'Matanzas',date:string};
type Sale={id:string,productId:string,qty:number,total:number,location:'Varadero'|'Matanzas',date:string};
type Movement={id:string,productId:string,qty:number,from:'Varadero'|'Matanzas',to:'Varadero'|'Matanzas',date:string};
type Removal={id:string,productId:string,qty:number,location:'Varadero'|'Matanzas',reason:string,date:string};
type DB={products:Product[],entries:Entry[],sales:Sale[],movements:Movement[],removals:Removal};
const KEY='libreta-almacen-v2';
const fresh=():DB=>({products:[],entries:[],sales:[],movements:[],removals:[]});
let db:DB=(()=>{try{return {...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fresh()}})();
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const today=()=>new Date().toLocaleDateString('es-ES');
const money=(n:number)=>n.toLocaleString('es-CU',{minimumFractionDigits:2,maximumFractionDigits:2})+' CUP';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function save(){localStorage.setItem(KEY,JSON.stringify(db));render(current)}
function prod(id:string){return db.products.find(p=>p.id===id)}
function options(){return db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
let current='resumen';

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`<header><h1>📦 Libreta Almacén</h1><p>Inventario Varadero ↔ Matanzas</p></header><nav>${[['resumen','Resumen'],['productos','Productos'],['entradas','Entradas'],['movimientos','Movimientos'],['ventas','Ventas'],['retiros','Retirar'],['inventario','Inventario']].map(([a,b])=>`<button data-p="${a}">${b}</button>`).join('')}</nav><main id="main"></main>`;
document.querySelectorAll<HTMLButtonElement>('nav button').forEach(b=>b.onclick=()=>render(current=b.dataset.p!));
function render(p:string){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p));const m=$<HTMLDivElement>('#main');if(p==='productos')products(m);else if(p==='entradas')entries(m);else if(p==='movimientos')moves(m);else if(p==='ventas')sales(m);else if(p==='retiros')removals(m);else if(p==='inventario')inventory(m);else summary(m)}
function products(m:HTMLDivElement){m.innerHTML=`<section class="card"><h2>Productos</h2><form id="f" class="grid"><input id="name" required placeholder="Nombre"><input id="price" type="number" min="0" step="0.01" required placeholder="Precio CUP"><input id="stock" type="number" min="0" required placeholder="Stock inicial"><button>Agregar</button></form></section><section class="card"><h2>Registrados</h2>${db.products.length?db.products.map(p=>`<div class="row"><b>${esc(p.name)}</b><span>${money(p.price)}</span><span>Varadero: ${p.varadero}</span><span>Matanzas: ${p.matanzas}</span><button onclick="editP('${p.id}')">Editar</button></div>`).join(''):'<p>No hay productos.</p>'}</section>`;$<HTMLFormElement>('#f').onsubmit=e=>{e.preventDefault();db.products.push({id:uid(),name:$<HTMLInputElement>('#name').value.trim(),price:+$<HTMLInputElement>('#price').value,varadero:+$<HTMLInputElement>('#stock').value,matanzas:0});save()}}
(window as any).editP=(id:string)=>{const p=prod(id);if(!p)return;const n=prompt('Nombre',p.name),v=prompt('Precio CUP',String(p.price));if(n!==null&&v!==null&&n.trim()&&+v>=0){p.name=n.trim();p.price=+v;save()}};
function entries(m:HTMLDivElement){m.innerHTML=`<section class="card"><h2>Entradas</h2><form id="f" class="grid"><select id="p" required>${options()}</select><input id="q" type="number" min="1" required placeholder="Cantidad"><select id="l"><option>Varadero</option><option>Matanzas</option></select><button>Registrar entrada</button></form></section><section class="card"><h2>Historial</h2>${db.entries.map(x=>`<div class="row">${x.date} · ${esc(prod(x.productId)?.name||'')} · +${x.qty} · ${x.location}</div>`).join('')||'<p>Sin entradas.</p>'}</section>`;$<HTMLFormElement>('#f').onsubmit=e=>{e.preventDefault();const p=prod($<HTMLSelectElement>('#p').value),q=+$<HTMLInputElement>('#q').value,l=$<HTMLSelectElement>('#l').value as 'Varadero'|'Matanzas';if(!p||q<=0)return;p[l.toLowerCase() as 'varadero'|'matanzas']+=q;db.entries.push({id:uid(),productId:p.id,qty:q,location:l,date:today()});save()}}
function moves(m:HTMLDivElement){m.innerHTML=`<section class="card"><h2>Movimiento entre tiendas</h2><form id="f" class="grid"><select id="p">${options()}</select><input id="q" type="number" min="1" required placeholder="Cantidad"><select id="from"><option>Varadero</option><option>Matanzas</option></select><select id="to"><option>Matanzas</option><option>Varadero</option></select><button>Registrar movimiento</button></form></section><section class="card"><h2>Historial</h2>${db.movements.map(x=>`<div class="row">${x.date} · ${esc(prod(x.productId)?.name||'')} · ${x.qty} · ${x.from} → ${x.to}</div>`).join('')||'<p>Sin movimientos.</p>'}</section>`;$<HTMLFormElement>('#f').onsubmit=e=>{e.preventDefault();const p=prod($<HTMLSelectElement>('#p').value),q=+$<HTMLInputElement>('#q').value,from=$<HTMLSelectElement>('#from').value as 'Varadero'|'Matanzas',to=$<HTMLSelectElement>('#to').value as 'Varadero'|'Matanzas';if(!p||from===to||q<=0)return;const fk=from.toLowerCase() as 'varadero'|'matanzas',tk=to.toLowerCase() as 'varadero'|'matanzas';if(p[fk]<q){alert('No hay suficiente stock en '+from);return}p[fk]-=q;p[tk]+=q;db.movements.push({id:uid(),productId:p.id,qty:q,from,to,date:today()});save()}}
function sales(m:HTMLDivElement){const total=db.sales.reduce((a,x)=>a+x.total,0);m.innerHTML=`<section class="card"><h2>Ventas</h2><form id="f" class="grid"><select id="p">${options()}</select><input id="q" type="number" min="1" required placeholder="Cantidad"><select id="l"><option>Varadero</option><option>Matanzas</option></select><button>Registrar venta</button></form></section><section class="card"><h2>Dinero recogido</h2><div class="big">${money(total)}</div></section><section class="card"><h2>Historial</h2>${db.sales.map(x=>`<div class="row">${x.date} · ${esc(prod(x.productId)?.name||'')} · ${x.qty} · ${money(x.total)} · ${x.location}</div>`).join('')||'<p>Sin ventas.</p>'}</section>`;$<HTMLFormElement>('#f').onsubmit=e=>{e.preventDefault();const p=prod($<HTMLSelectElement>('#p').value),q=+$<HTMLInputElement>('#q').value,l=$<HTMLSelectElement>('#l').value as 'Varadero'|'Matanzas';if(!p||q<=0)return;const k=l.toLowerCase() as 'varadero'|'matanzas';if(p[k]<q){alert('Stock insuficiente en '+l);return}p[k]-=q;db.sales.push({id:uid(),productId:p.id,qty:q,total:q*p.price,location:l,date:today()});save()}}
function removals(m:HTMLDivElement){m.innerHTML=`<section class="card"><h2>Retirar producto</h2><form id="f" class="grid"><select id="p">${options()}</select><input id="q" type="number" min="1" required placeholder="Cantidad"><select id="l"><option>Varadero</option><option>Matanzas</option></select><input id="r" required placeholder="Motivo: daño, rotura, etc."><button>Registrar retiro</button></form></section><section class="card"><h2>Historial</h2>${db.removals.map(x=>`<div class="row">${x.date} · ${esc(prod(x.productId)?.name||'')} · ${x.qty} · ${x.location} · ${esc(x.reason)}</div>`).join('')||'<p>Sin retiros.</p>'}</section>`;$<HTMLFormElement>('#f').onsubmit=e=>{e.preventDefault();const p=prod($<HTMLSelectElement>('#p').value),q=+$<HTMLInputElement>('#q').value,l=$<HTMLSelectElement>('#l').value as 'Varadero'|'Matanzas',r=$<HTMLInputElement>('#r').value.trim();if(!p||q<=0||!r)return;const k=l.toLowerCase() as 'varadero'|'matanzas';if(p[k]<q){alert('Stock insuficiente en '+l);return}p[k]-=q;db.removals.push({id:uid(),productId:p.id,qty:q,location:l,reason:r,date:today()});save()}}
function inventory(m:HTMLDivElement){m.innerHTML=`<section class="card"><h2>Inventario actual</h2><div class="table"><div class="th"><b>Producto</b><b>Varadero</b><b>Matanzas</b><b>Total</b></div>${db.products.map(p=>`<div class="tr"><b>${esc(p.name)}</b><span>${p.varadero}</span><span>${p.matanzas}</span><strong>${p.varadero+p.matanzas}</strong></div>`).join('')||'<p>No hay productos.</p>'}</div></section>`}
function summary(m:HTMLDivElement){const units=db.products.reduce((a,p)=>a+p.varadero+p.matanzas,0),sold=db.sales.reduce((a,x)=>a+x.qty,0),cash=db.sales.reduce((a,x)=>a+x.total,0);m.innerHTML=`<section class="hero"><h2>Resumen general</h2><p>Datos guardados automáticamente en este teléfono.</p></section><div class="cards"><div class="stat"><b>${db.products.length}</b><span>Productos</span></div><div class="stat"><b>${units}</b><span>Unidades en stock</span></div><div class="stat"><b>${sold}</b><span>Unidades vendidas</span></div><div class="stat"><b>${db.movements.length}</b><span>Movimientos</span></div><div class="stat"><b>${db.removals.length}</b><span>Retiros</span></div><div class="stat"><b>${money(cash)}</b><span>Dinero de ventas</span></div></div>`}
render(current);
